Fixed bug in dtag-confusion script which caused erroneous confusions (because of bad source text file name recognition).
git-svn-id: https://copenhagen-dependency-treebank.googlecode.com/svn/trunk@1635 f735436f-cb49-0410-a0ae-73795322737e

diff --git a/tools/dtag-status b/tools/dtag-status
--- a/tools/dtag-status
+++ b/tools/dtag-status
@@ -1,33 +1,35 @@
 #!/bin/bash
 
-# Check that file exists
-file=$1
-if [ ! -f $file ] ; then
-	echo "ERROR: unknown file $file";
-	exit 1;
-fi
+for file in $* ; do 
+	# Check that file exists
+	if [ ! -f $file ] ; then
+		echo "ERROR: unknown file $file";
+		exit 1;
+	fi
 
-# Report svn properties
-svn proplist -v $file | tr '\n' '%' | sed -e 's/%  \([^ ]\)/\n  \1/g' -e 's/%    /: /g' | sed -e 's/%/\n/g' -e "s/Properties on '//g" -e "s/'//g"
+	# Report svn properties
+	svn proplist -v $file | tr '\n' '%' | sed -e 's/%  \([^ ]\)/\n  \1/g' -e 's/%    /: /g' | sed -e 's/%/\n/g' -e "s/Properties on '//g" -e "s/'//g" | grep -v 'svn:mergeinfo'
 
-# Report number of words/sentences
-words=0
-sents=0
-prefix=`echo $file | sed -e 's/\([0-9]\)-[^0-9]*$/\1/g'`;
-for f in `ls $file $prefix*.tag` ; do
-	nword=`cat $f | grep '</W>' | wc -l`
-	nsent=`cat $f | grep '</s>' | wc -l`
-	if [ $words -lt $nword ] ; then words=$nword ; fi
-	if [ $sents -lt $nsent ] ; then sents=$nsent ; fi
+	# Report number of words/sentences
+	words=0
+	sents=0
+	prefix=`echo $file | sed -e 's/\([0-9]\)-[^0-9]*$/\1/g'`;
+	for f in `ls $file $prefix*.tag 2>/dev/null` ; do
+		nword=`cat $f | grep '</W>' | wc -l`
+		nsent=`cat $f | grep '</s>' | wc -l`
+		if [ $words -lt $nword ] ; then words=$nword ; fi
+		if [ $sents -lt $nsent ] ; then sents=$nsent ; fi
+	done
+	if [ $words -gt 0 ] ; then
+		echo "  tokens: $words"
+		echo "  sentences: $sents"
+	fi
+
+	# Report error statistics
+	efile=`echo $file | sed -e 's/.tag$/.err/g'`
+	if [ -f "$efile" ] ; then 
+		echo ""
+		echo "Last error counts (use \"errors\" command for details and update): "
+		cat $efile | grep -v '>' | awk -F": " '{ print $2 }' | sed -e "s/ /\n/g" | sed -e 's/$/ error/' | sort | uniq -c | grep -v redirect 
+	fi
 done
-echo "  tokens: $words"
-echo "  sentences: $sents"
-
-# Report error statistics
-efile=`echo $file | sed -e 's/.tag$/.err/g'`
-echo ""
-echo "Error counts (use \"errors\" command for details): "
-if [ -f "$efile" ] ; then 
-	cat $efile | grep -v '>' | awk -F": " '{ print $2 }' | sed -e "s/ /\n/g" | sed -e 's/$/ error/' | sort | uniq -c | grep -v redirect 
-fi
-
