Added lots of status commands.
git-svn-id: https://copenhagen-dependency-treebank.googlecode.com/svn/trunk@798 f735436f-cb49-0410-a0ae-73795322737e

diff --git a/tools/dtag-closetask b/tools/dtag-closetask
--- a/tools/dtag-closetask
+++ b/tools/dtag-closetask
@@ -8,6 +8,11 @@ if [ -z "$name" ] ; then
     exit 0
 fi
 
+if ! ~/cdt/tools/dtag-setstatus $* ; then
+	echo -e "\nERROR: You forgot to update the annotation status!";
+	exit 1;
+fi
+
 # Find first task
 todo="todo/$name"
 cd "$HOME"/cdt
